/**
 * 0. class name
 * 1. engRegular
 * 2. engShift
 * 3. rusRegular
 * 4. rusShift
 */

export let keyArr = [
  ["Backquote", "`", "~", "Ё", "ё"],
  ["Digit1", "1", "1", "1", "1", "!"],
  ["Digit2", "2", "2", "2", "2", "@"],
  ["Digit3", "3", "3", "3", "3", "#"],
  ["Digit4", "4", "4", "4", "4", "$"],
  ["Digit5", "5", "5", "5", "5", "%"],
  ["Digit6", "6", "6", "6", "6", "^"],
  ["Digit7", "7", "7", "7", "7", "&"],
  ["Digit8", "8", "8", "8", "8", "*"],
  ["Digit9", "9", "9", "9", "9", "("],
  ["Digit0", "0", "0", "0", "0", ")"],
  ["Minus", "-", "-", "-", "-", "_"],
  ["Equal", "=", "=", "=", "=", "+"],
  ["Backspace", "Backspace"],
  ["Tab", "Tab"],
  ["KeyQ", "q", "Q", "Й", "й"],
  ["KeyW", "w", "W", "Ц", "ц"],
  ["KeyE", "e", "E", "У", "у"],
  ["KeyR", "r", "R", "К", "к"],
  ["KeyT", "t", "T", "Е", "е"],
  ["KeyY", "y", "Y", "Н", "н"],
  ["KeyU", "u", "U", "Г", "г"],
  ["KeyI", "i", "I", "Ш", "ш"],
  ["KeyO", "o", "O", "Щ", "щ"],
  ["KeyP", "p", "P", "З", "з"],
  ["BracketLeft", "[", "{", "Х", "х"],
  ["BracketRight", "]", "}", "Ъ", "ъ"],
  ["Backslash", "\\", "/"],
  ["Delete", "Del"],
  ["CapsLock", "Caps Lock"],
  ["KeyA", "a", "A", "Ф", "ф"],
  ["KeyS", "s", "S", "Ы", "ы"],
  ["KeyD", "d", "D", "В", "в"],
  ["KeyF", "f", "F", "А", "а"],
  ["KeyG", "g", "G", "П", "п"],
  ["KeyH", "h", "H", "Р", "р"],
  ["KeyJ", "j", "J", "О", "о"],
  ["KeyK", "k", "K", "Л", "л"],
  ["KeyL", "l", "L", "Д", "д"],
  ["Semicolon", ";", ":", "Ж", "ж"],
  ["Quote", "'", '"', "Э", "э"],
  ["Enter", "Enter"],
  ["ShiftLeft", "Shift"],
  ["KeyZ", "z", "Z", "Я", "я"],
  ["KeyX", "x", "X", "Ч", "ч"],
  ["KeyC", "c", "C", "С", "с"],
  ["KeyV", "v", "V", "М", "м"],
  ["KeyB", "b", "B", "И", "и"],
  ["KeyN", "n", "N", "Т", "т"],
  ["KeyM", "m", "M", "Ь", "ь"],
  ["Comma", ",", "<", "Б", "б"],
  ["Period", ".", ">", "Ю", "ю"],
  ["Slash", "/", "?", ".", ","],
  ["ArrowUp", "▲", "▲"],
  ["ShiftRight", "Shift"],
  ["ControlLeft", "Ctrl"],
  ["MetaLeft", "Win"],
  ["AltLeft", "Alt"],
  ["Space", "", ""],
  ["AltRight", "Alt"],
  ["ArrowLeft", "◄", "◄"],
  ["ArrowDown", "▼", "▼"],
  ["ArrowRight", "►", "►"],
  ["ControlRight", "Ctrl"],
];
